### ISSUE TITLE
ImportError: cannot import name 'validate_v2_spec' from 'openapi_spec_validator'

### ISSUE THREAD

**Issue by Milind-TW** [p1c2u/openapi-spec-validator#178]
We are seeing the below error with openapi-spec-validator>=0.5.0:

```
ImportError: cannot import name 'validate_v2_spec' from 'openapi_spec_validator' (/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/openapi_spec_validator/__init__.py)
Error: Process completed with exit code 1.
```

Python version used: **3.10.6**

Observation: Everything works as expecetd if we use versions <= 0.4.0. Seems to be a bug in 0.5.0

Complete stack trace:

```
Traceback (most recent call last):
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "test.py", line 59, in load
    return load_api_def(os.path.join(spec_dir, spec))
  File "test.py", line 19, in load_api_def
    return ResolvingParser(path).specification
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/prance/__init__.py", line 291, in __init__
    BaseParser.__init__(self, url=url, spec_string=spec_string, lazy=lazy, **kwargs)
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/prance/__init__.py", line 116, in __init__
    self.parse()
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/prance/__init__.py", line 146, in parse
    self._validate()
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/prance/__init__.py", line 322, in _validate
    BaseParser._validate(self)
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/prance/__init__.py", line 185, in _validate
    validator(parsed)
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/prance/__init__.py", line 229, in _validate_openapi_spec_validator
    from openapi_spec_validator import validate_v2_spec, validate_v3_spec
ImportError: cannot import name 'validate_v2_spec' from 'openapi_spec_validator' (/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/openapi_spec_validator/__init__.py)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 158, in <module>
    generate(
  File "test.py", line 120, in generate
    specs = pool.map(
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/usercache/Python/3.10.6/x64/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ImportError: cannot import name 'validate_v2_spec' from 'openapi_spec_validator' (/opt/usercache/Python/3.10.6/x64/lib/python3.10/site-packages/openapi_spec_validator/__init__.py)
Error: Process completed with exit code 1.
```

Thanks in advance!

**Comment by p1c2u** [comment]
Hi @Milind-TW 

this is one of the backward incompatibilities of version 0.5.x

Please see [release](https://github.com/p1c2u/openapi-spec-validator/releases/tag/0.5.0) notes

**Comment by Milind-TW** [comment]
Thanks for your quick response @p1c2u. We have identified that the issue is with a different module that uses openapi-spec-validator in the background and imports an incompatible shortcut. We can close this now.
