### ISSUE TITLE
AttributeError: module 'jsonschema._validators' has no attribute 'properties_draft4'

### ISSUE THREAD

**Issue by rykerrumsey** [p1c2u/openapi-spec-validator#48]
When I run the command **openapi-spec-validator** I'm getting this weird error. Was my version installed funny? 

```
Traceback (most recent call last):
  File "/home/rykerrumsey/.local/share/virtualenvs/flask_api-JlfD7WU8/bin/openapi-spec-validator", line 7, in <module>
    from openapi_spec_validator.__main__ import main
  File "/home/rykerrumsey/.local/share/virtualenvs/flask_api-JlfD7WU8/lib/python3.6/site-packages/openapi_spec_validator/__init__.py", line 7, in <module>
    from openapi_spec_validator.factories import JSONSpecValidatorFactory
  File "/home/rykerrumsey/.local/share/virtualenvs/flask_api-JlfD7WU8/lib/python3.6/site-packages/openapi_spec_validator/factories.py", line 5, in <module>
    from openapi_spec_validator.generators import (
  File "/home/rykerrumsey/.local/share/virtualenvs/flask_api-JlfD7WU8/lib/python3.6/site-packages/openapi_spec_validator/generators.py", line 12, in <module>
    class SpecValidatorsGeneratorFactory:
  File "/home/rykerrumsey/.local/share/virtualenvs/flask_api-JlfD7WU8/lib/python3.6/site-packages/openapi_spec_validator/generators.py", line 19, in SpecValidatorsGeneratorFactory
    'properties': _validators.properties_draft4,
AttributeError: module 'jsonschema._validators' has no attribute 'properties_draft4'
```

**Comment by rykerrumsey** [comment]
I believe the error is from installing connexion. Works fine when standalone in a environment.
