### ISSUE TITLE
jsonschema 3.0+ support

### ISSUE THREAD

**Issue by strongbugman** [p1c2u/openapi-spec-validator#54]
Hi, the jsonschema has been updated to [3.0+](https://github.com/Julian/jsonschema/releases), and maybe has some break changes:
```shell
.eggs/openapi_spec_validator-0.2.4-py3.6.egg/openapi_spec_validator/__init__.py:7: in <module>
    from openapi_spec_validator.factories import JSONSpecValidatorFactory
.eggs/openapi_spec_validator-0.2.4-py3.6.egg/openapi_spec_validator/factories.py:5: in <module>
    from openapi_spec_validator.generators import (
.eggs/openapi_spec_validator-0.2.4-py3.6.egg/openapi_spec_validator/generators.py:12: in <module>
    class SpecValidatorsGeneratorFactory:
.eggs/openapi_spec_validator-0.2.4-py3.6.egg/openapi_spec_validator/generators.py:19: in SpecValidatorsGeneratorFactory
    'properties': _validators.properties_draft4,
E   AttributeError: module 'jsonschema._validators' has no attribute 'properties_draft4'
```

**Comment by p1c2u** [comment]
It was fixed with #590.2.5 and version 0.2.5

**Comment by timoilya** [comment]
I have same problem on python3.6.7
openapi-spec-validator==0.2.6
jsonschema==3.0.1
```bash
MacBook-Pro-ilya:projects ilya$ pip -V
pip 19.0.3 from /Users/ilya/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pip (python 3.6)
MacBook-Pro-ilya:projects ilya$ pip show openapi_spec_validator
Name: openapi-spec-validator
Version: 0.2.6
Summary: UNKNOWN
Home-page: https://github.com/p1c2u/openapi-spec-validator
Author: Artur Maciag
Author-email: maciag.artur@gmail.com
License: Apache License, Version 2.0
Location: /Users/ilya/.pyenv/versions/3.6.7/lib/python3.6/site-packages
Requires: pathlib, PyYAML, jsonschema, six
Required-by: 
MacBook-Pro-ilya:projects ilya$ pip show jsonschema
Name: jsonschema
Version: 3.0.1
Summary: An implementation of JSON Schema validation for Python
Home-page: https://github.com/Julian/jsonschema
Author: Julian Berman
Author-email: Julian@GrayVines.com
License: UNKNOWN
Location: /Users/ilya/.pyenv/versions/3.6.7/lib/python3.6/site-packages
Requires: setuptools, pyrsistent, six, attrs
Required-by: openapi-spec-validator, jsonmerge
MacBook-Pro-ilya:projects ilya$ /Users/ilya/.pyenv/versions/3.6.7/bin/python
Python 3.6.7 (default, Mar 13 2019, 14:00:09) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openapi_spec_validator import validate_v3_spec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilya/.pyenv/versions/3.6.7/lib/python3.6/site-packages/openapi_spec_validator/__init__.py", line 7, in <module>
    from openapi_spec_validator.factories import JSONSpecValidatorFactory
  File "/Users/ilya/.pyenv/versions/3.6.7/lib/python3.6/site-packages/openapi_spec_validator/factories.py", line 5, in <module>
    from openapi_spec_validator.generators import (
  File "/Users/ilya/.pyenv/versions/3.6.7/lib/python3.6/site-packages/openapi_spec_validator/generators.py", line 12, in <module>
    class SpecValidatorsGeneratorFactory:
  File "/Users/ilya/.pyenv/versions/3.6.7/lib/python3.6/site-packages/openapi_spec_validator/generators.py", line 19, in SpecValidatorsGeneratorFactory
    'properties': _validators.properties_draft4,
AttributeError: module 'jsonschema._validators' has no attribute 'properties_draft4'
>>> 
```

**Comment by timoilya** [comment]
@strongbugman , do you still have that problem?

**Comment by strongbugman** [comment]
@timoilya 
```
openapi-spec-validator 0.2.6 has requirement jsonschema<3, but you'll have jsonschema 3.0.1 which is incompatible.
```

**Comment by timoilya** [comment]
@strongbugman , this ussue is closed, but jsonschema >3 is not supported in version 0.2.5
https://github.com/p1c2u/openapi-spec-validator/issues/54#issuecomment-467098215

**Comment by BenTaub** [comment]
I am having the same issue - openapi-spec-validator 0.2.6 and jsonschema 3.0.1 delivering the following error:
`AttributeError: module 'jsonschema._validators' has no attribute 'properties_draft4'`

Does @strongbugman 's comment mean I should step the spec validator back to a version lower than 0.2.5?

**Comment by strongbugman** [comment]
Yes, or you can create a PR to fix the compatibility problem

Ben <notifications@github.com> 于2019年4月14日周日 上午6:56写道：

**Comment by timoilya** [comment]
@strongbugman , please review PR https://github.com/p1c2u/openapi-spec-validator/pull/72 if you may to approve it
